/**
 * The container NDJSON sidecar, read the way production reads it — through the
 * REAL shell command, against a REAL file, written by the REAL producer.
 *
 * ── Why this file exists ────────────────────────────────────────────────────
 * `drainContainerBootTelemetry` never truncates `/var/log/ezil-telemetry.ndjson`
 * and runs after EVERY `ensureDesktop` call, warm ones included. So the same
 * lines are read over and over for as long as the container lives, and until
 * this change each read minted a fresh `crypto.randomUUID()` per line — which
 * is precisely the column (`event_id`) that the app's `ingestBatch` dedupes on
 * with `ON CONFLICT DO NOTHING`. One boot phase would therefore have landed as
 * N rows, N counting how many times the user opened the desktop, and no query
 * downstream could have told the duplicates from real events.
 *
 * The unit tests in `./telemetry.test.ts` cover the parser's field mapping.
 * What is tested HERE is the property that unit-level mocking cannot reach:
 * feed the pipeline a growing file the way the real thing grows, read it twice
 * through the actual `sh` command, and demand that the lines present in both
 * reads come out with byte-identical ids.
 *
 * The fixture lines are not typed out here either — they are generated by
 * `emit_telemetry()` lifted verbatim out of `scripts/start-neko.sh`, so a
 * change to that `printf` format is caught here rather than in production.
 *
 * ── Three tests, not the file, are GNU-coreutils-only ───────────────────────
 * `containerTelemetryTailCommand` (`./telemetry.ts`) is a command for the
 * CONTAINER — Ubuntu, GNU coreutils — and these three tests are the ones that
 * run it for real and then depend on its metadata line parsing. Two GNU-isms
 * bite when the same string is handed to a Mac's own shell:
 *
 *   * `wc -c < file` — GNU prints the count bare; BSD/macOS RIGHT-ALIGNS it in
 *     a space-padded field, so the emitted line is `... bytes=       42
 *     inode=0`. `CONTAINER_TELEMETRY_META_RE` anchors `bytes=(\d+)` and the
 *     padding sits INSIDE the line, where the parser's `head.trim()` cannot
 *     reach it, so the meta line does not parse at all. The parser then
 *     degrades exactly as designed (whole stdout treated as the tail, no
 *     offset) — which is correct behaviour and makes all three assertions
 *     false: `tail.raw.startsWith('{')`, `startByteOffset > 0`, and stable
 *     event ids across re-reads.
 *   * `stat -c %i` — GNU only; BSD `stat` has no `-c` and the command's own
 *     `2>/dev/null || echo 0` turns that into a silent `inode=0`.
 *
 * MEASURED, not assumed, on this Linux box with stubs on PATH:
 *   * `stat` alone (rejects -c, usage to stderr, exit 1) -> 12 pass / 1 fail —
 *     only "reports the file size and inode". This is what M3 measured, and it
 *     is why M3 could gate one test and had to leave two running.
 *   * `wc` alone (delegates the count, reprints it as `printf '%8d'`) ->
 *     10 pass / 3 fail — ALL THREE, by the same names as the real macOS leg.
 *   * both together -> 10 pass / 3 fail, identical.
 * PR #14's eighth run, macOS (job 100991453440), failed exactly these three.
 * So the open question M3 recorded is answered: it is `wc`, not `stat`, and
 * the two "unexplained" failures were never a second mechanism.
 *
 * The command is not wrong — it never runs anywhere but inside the image. What
 * is not portable is executing a container command against a BSD userland, so
 * these three are gated on the userland, and the other ten (parser contract,
 * degradation, id derivation from literal fixtures) keep running everywhere.
 *
 * A portable `containerTelemetryTailCommand` would let all thirteen run on a
 * Mac — `wc -c ... | tr -d ' '` is the whole change — but `./telemetry.ts` is
 * not this row's to edit; see the M4 report's hand-off.
 */
import { describe, expect, it, beforeEach, afterEach } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/** Why three assertions below may not run here. `null` means they CAN. Same
 *  idiom as `./browser-sidecar.container.test.ts`'s `SKIP_REASON`. */
const LINUX_ONLY_REASON = process.platform === 'linux'
    ? null
    : `containerTelemetryTailCommand is a GNU-coreutils command for the container image: BSD `
    + `\`wc -c\` space-pads its count (so the bytes=/inode= meta line does not parse) and BSD `
    + `\`stat\` has no -c (so inode degrades to 0). Both MEASURED with stubs on Linux; running `
    + `the container's command against ${process.platform}'s userland is not meaningful`;

if (LINUX_ONLY_REASON) {
    console.warn(
        `\n${'='.repeat(78)}\n`
        + `SKIPPING three tests in the container-tail suite: ${LINUX_ONLY_REASON}.\n`
        + `The other ten (parser contract, degradation, id derivation) still run.\n`
        + `${'='.repeat(78)}\n`,
    );
}

const itIf = LINUX_ONLY_REASON ? it.skip : it;

import {
  CONTAINER_TELEMETRY_META_PREFIX,
  containerTelemetryTailCommand,
  parseContainerTelemetryLines,
  parseContainerTelemetryTail,
  stableTelemetryEventId,
} from './telemetry';

/** Same values `index.ts` passes in production. */
const MAX_BYTES = 65_536;

/** `emit_telemetry()`, lifted out of the shipped script rather than retyped. */
function emitTelemetrySource(): string {
  const script = readFileSync(join(import.meta.dir, '..', 'scripts', 'start-neko.sh'), 'utf8');
  const match = script.match(/^emit_telemetry\(\) \{\n[\s\S]*?^\}$/m);
  if (!match) throw new Error('emit_telemetry() not found in scripts/start-neko.sh — this test is stale');
  return match[0];
}

let dir: string;
let logPath: string;

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'ezil-tel-'));
  logPath = join(dir, 'ezil-telemetry.ndjson');
});
afterEach(() => rmSync(dir, { recursive: true, force: true }));

/** Run the REAL producer: append one phase line, exactly as a container does. */
function emit(phase: string, status: string, durationMs: number): void {
  const res = spawnSync(
    'sh',
    ['-c', `TELEMETRY_NDJSON='${logPath}'\n${emitTelemetrySource()}\nemit_telemetry '${phase}' '${status}' ${durationMs}`],
    { encoding: 'utf8' },
  );
  expect(res.status).toBe(0);
}

/** Run the REAL read command and take it all the way to parsed events. */
function readAndParse(sandboxId: string | null = 'guac-abc-def') {
  const res = spawnSync('sh', ['-c', containerTelemetryTailCommand(logPath, MAX_BYTES)], { encoding: 'utf8' });
  expect(res.status).toBe(0);
  expect(res.stderr).toBe('');
  const tail = parseContainerTelemetryTail(res.stdout);
  const events = parseContainerTelemetryLines(tail.raw, {
    correlationId: `cid-${Math.random()}`, // a NEW request every read, as in production
    sandboxId: sandboxId ?? undefined,
    tailStartByteOffset: tail.startByteOffset,
    logInode: tail.inode,
    now: new Date(), // a NEW clock every read, as in production
  });
  return { tail, events };
}

describe('container NDJSON tail — the real command against a real file', () => {
  itIf('reports the file size and inode, and separates them from the NDJSON', () => {
    emit('container_start', 'ok', 312);
    const { tail, events } = readAndParse();

    expect(tail.raw.startsWith('{')).toBe(true);
    expect(tail.raw).not.toContain(CONTAINER_TELEMETRY_META_PREFIX);
    expect(tail.startByteOffset).toBe(0); // whole file fits in the window
    expect(Number(tail.inode)).toBeGreaterThan(0);
    expect(events).toHaveLength(1);
    expect(events[0]).toMatchObject({ source: 'container', site: 'container_start', outcome: 'ok', durationMs: 312 });
  });

  it('degrades cleanly on a file that does not exist — no events, no throw, no stderr', () => {
    const { tail, events } = readAndParse();
    expect(tail.raw).toBe('');
    expect(tail.inode).toBe('0');
    expect(events).toEqual([]);
  });

  itIf('🔴 gives a re-read line the SAME eventId, and only the new lines new ids', () => {
    emit('container_start', 'ok', 312);
    emit('workspace_mount', 'skipped', 0);
    emit('ready', 'ok', 21900);
    const first = readAndParse().events;
    expect(first).toHaveLength(3);

    // The user opens the desktop again. `start-neko.sh` appends to the SAME
    // file; nothing truncated it, and the Worker reads the whole thing again.
    emit('container_start', 'skipped', 0);
    emit('ready', 'ok', 27);
    const second = readAndParse().events;
    expect(second).toHaveLength(5);

    const firstIds = first.map((e) => e.eventId);
    const secondIds = second.map((e) => e.eventId);
    // The three already-shipped lines keep their identity byte for byte...
    expect(secondIds.slice(0, 3)).toEqual(firstIds);
    // ...and the two genuinely new ones are genuinely new.
    expect(new Set(secondIds).size).toBe(5);
    expect(secondIds.slice(3).some((id) => firstIds.includes(id))).toBe(false);
  });

  it('🔴 keeps two byte-identical lines in one file distinct (offset, not content, is the discriminator)', () => {
    // `workspace_mount skipped 0` is emitted verbatim on every relaunch — the
    // exact case a content-only hash would silently collapse into one row.
    emit('workspace_mount', 'skipped', 0);
    emit('workspace_mount', 'skipped', 0);
    const { events } = readAndParse();
    expect(events).toHaveLength(2);
    expect(events[0]!.eventId).not.toBe(events[1]!.eventId);
  });

  itIf('🔴 keeps ids stable once the file outgrows the 64 KiB window and the tail slides', () => {
    // Fill past the window with real producer lines, then read, append, re-read.
    const filler = Buffer.alloc(MAX_BYTES, 'x').toString();
    writeFileSync(logPath, `# ${filler}\n`); // non-JSON prologue: dropped by the parser, still shifts offsets
    for (let i = 0; i < 40; i++) emit('desktop_ready_wait', 'ok', 1000 + i);

    const first = readAndParse();
    expect(first.tail.startByteOffset).toBeGreaterThan(0); // the window really did slide
    const firstIds = new Map(first.events.map((e) => [e.durationMs, e.eventId]));
    expect(firstIds.size).toBeGreaterThan(30);

    emit('ready', 'ok', 5);
    const second = readAndParse();
    for (const e of second.events) {
      const before = firstIds.get(e.durationMs);
      if (before !== undefined) expect(e.eventId).toBe(before);
    }
  });

  it('separates two sandboxes that wrote identical bytes at identical offsets', () => {
    emit('container_start', 'ok', 312);
    const a = readAndParse('guac-user-a').events;
    const b = readAndParse('guac-user-b').events;
    expect(a[0]!.eventId).not.toBe(b[0]!.eventId);
  });

  it('falls back to fresh random ids when there is no sandboxId — a duplicate, never a mix-up', () => {
    emit('container_start', 'ok', 312);
    const a = readAndParse(null).events;
    const b = readAndParse(null).events;
    expect(a[0]!.eventId).not.toBe(b[0]!.eventId);
  });

  it('every id is a UUID the app`s `uuid` column and zod schema will accept', () => {
    emit('container_start', 'ok', 312);
    emit('ready', 'error', 180000);
    for (const e of readAndParse().events) {
      expect(e.eventId).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    }
  });
});

describe('parseContainerTelemetryTail', () => {
  it('treats unrecognised stdout as all-tail and reports no offset, rather than inventing one', () => {
    const out = parseContainerTelemetryTail('{"eventClass":"boot_phase","site":"x","code":"ok","outcome":"ok"}\n');
    expect(out.startByteOffset).toBeUndefined();
    expect(out.inode).toBe('0');
    expect(out.raw.startsWith('{')).toBe(true);
    // ...and with no offset, ids fall back to random: a duplicate row, not a
    // wrong one.
    const ctx = { correlationId: 'c', sandboxId: 's', logInode: out.inode };
    const one = parseContainerTelemetryLines(out.raw, { ...ctx, tailStartByteOffset: out.startByteOffset });
    const two = parseContainerTelemetryLines(out.raw, { ...ctx, tailStartByteOffset: out.startByteOffset });
    expect(one[0]!.eventId).not.toBe(two[0]!.eventId);
  });

  it('never lets the offset go negative when the reported size is smaller than the tail', () => {
    const out = parseContainerTelemetryTail(`${CONTAINER_TELEMETRY_META_PREFIX} bytes=2 inode=9\n{"a":1}\n`);
    expect(out.startByteOffset).toBe(0);
    expect(out.inode).toBe('9');
  });
});

describe('stableTelemetryEventId', () => {
  it('is a pure function of its parts — same in, same out, forever', () => {
    const parts = ['container', 'guac-a-b', '1234', '512', '{"site":"ready"}'];
    expect(stableTelemetryEventId(parts)).toBe(stableTelemetryEventId([...parts]));
  });

  it('changes when ANY part changes, including at a part boundary', () => {
    const base = ['container', 'guac-a-b', '1234', '512', 'line'];
    const ids = new Set([
      stableTelemetryEventId(base),
      stableTelemetryEventId(['container', 'guac-a-c', '1234', '512', 'line']),
      stableTelemetryEventId(['container', 'guac-a-b', '1235', '512', 'line']),
      stableTelemetryEventId(['container', 'guac-a-b', '1234', '513', 'line']),
      stableTelemetryEventId(['container', 'guac-a-b', '1234', '512', 'line2']),
      // a boundary that a naive join would confuse with the base
      stableTelemetryEventId(['container', 'guac-a-b', '1234', '512l', 'ine']),
    ]);
    expect(ids.size).toBe(6);
  });

  it('spreads over a realistic corpus without a single collision', () => {
    const ids = new Set<string>();
    for (let offset = 0; offset < 5000; offset++) {
      ids.add(stableTelemetryEventId(['container', 'guac-a-b', '77', String(offset), 'workspace_mount skipped 0']));
    }
    expect(ids.size).toBe(5000);
  });
});
