-- ezil_computers — the top-level "your computer" unit. See
-- src/server/db/schema/computers.ts for the full design rationale.
--
-- NOTE: `auth.users` already exists (it is Supabase Auth's own table) — it
-- is intentionally NOT created here. `src/server/db/schema/auth-users.ts`
-- only *references* it so Drizzle can resolve the FK below; drizzle-kit's
-- autogenerated migration included a `CREATE SCHEMA "auth"` / `CREATE TABLE
-- "auth"."users"` pair (since it doesn't know the referenced table already
-- exists), which has been removed by hand from this file.
CREATE TABLE "ezil_computers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text DEFAULT 'Computer' NOT NULL,
	"slot" smallint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_opened_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"metadata" jsonb,
	CONSTRAINT "ezil_computers_slot_chk" CHECK ("ezil_computers"."slot" in (1, 2))
);
--> statement-breakpoint
ALTER TABLE "ezil_computers" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE "ezil_computers" ADD CONSTRAINT "ezil_computers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE cascade;
--> statement-breakpoint
CREATE UNIQUE INDEX "ezil_computers_user_slot_uidx" ON "ezil_computers" USING btree ("user_id","slot") WHERE "ezil_computers"."deleted_at" is null;
--> statement-breakpoint
CREATE INDEX "idx_ezil_computers_user_id" ON "ezil_computers" USING btree ("user_id") WHERE "ezil_computers"."deleted_at" is null;
--> statement-breakpoint

-- Owner can read/insert/update/soft-delete (via UPDATE of deleted_at) their
-- own computers. There is deliberately no DELETE policy — this table is
-- soft-delete only (see the schema file's doc comment); a real DELETE is
-- rejected by RLS by default (no policy grants that command), on top of
-- application code never issuing one.
CREATE POLICY "Users can read own computers"
    ON "ezil_computers"
    FOR SELECT
    USING (user_id = auth.uid());
--> statement-breakpoint
CREATE POLICY "Users can insert own computers"
    ON "ezil_computers"
    FOR INSERT
    WITH CHECK (user_id = auth.uid());
--> statement-breakpoint
CREATE POLICY "Users can update own computers"
    ON "ezil_computers"
    FOR UPDATE
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
--> statement-breakpoint

-- Service role (this app's own Postgres connection — src/server/db/index.ts)
-- gets full access. The tRPC router is the actual enforcement point for
-- end-user requests (it always filters by the authenticated ctx.user.id);
-- this policy is defense-in-depth for any direct PostgREST/Supabase-client
-- access path.
CREATE POLICY "Service role full access computers"
    ON "ezil_computers"
    FOR ALL
    USING (auth.role() = 'service_role');
