/** Development diagnostics only. Production still validates through src/env.ts. */
export type Environment = Record<string, string | undefined>;
export type Diagnostic = { name: string; code: 'missing' | 'invalid' | 'local_only' | 'must_be_unset' };

export const LOCAL_PROJECT = 'ezil-os-web-dev';
export const LOCAL_API_URL = 'http://127.0.0.1:55321';
export const ENV_HEADER = '# Generated by EZiL local web setup v1.\n';

export function isLocalDockerEndpoint(value: string): boolean {
    return /^(unix:\/\/\/[^\r\n]+|npipe:\/\/\/[^\r\n]+)$/.test(value);
}

export function isLocalApiUrl(value: string): boolean {
    return value === LOCAL_API_URL;
}

export function isLocalDatabaseUrl(value: string): boolean {
    try {
        const url = new URL(value);
        return url.protocol === 'postgresql:' && url.hostname === '127.0.0.1'
            && url.port === '55322' && url.pathname === '/postgres'
            && url.username === 'postgres' && !!url.password && !url.search && !url.hash;
    } catch {
        return false;
    }
}

export function checkDevelopmentEnvironment(env: Environment, local = false): Diagnostic[] {
    const issues: Diagnostic[] = [];
    const add = (name: string, code: Diagnostic['code']) => issues.push({ name, code });
    for (const name of ['SUPABASE_DATABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY']) {
        if (!env[name]?.trim()) add(name, 'missing');
    }
    for (const [name, protocols] of [
        ['SUPABASE_DATABASE_URL', ['postgres:', 'postgresql:']],
        ['NEXT_PUBLIC_SUPABASE_URL', ['http:', 'https:']],
    ] as const) {
        if (!env[name]?.trim()) continue;
        try {
            const url = new URL(env[name]);
            if (!(protocols as readonly string[]).includes(url.protocol) || !url.hostname) add(name, 'invalid');
        } catch {
            add(name, 'invalid');
        }
    }
    if (env.CRON_SECRET !== undefined && env.CRON_SECRET.length < 32) add('CRON_SECRET', 'invalid');
    if (env.EZIL_OS_ACCESS_MODE !== undefined && !['invite', 'open'].includes(env.EZIL_OS_ACCESS_MODE)) {
        add('EZIL_OS_ACCESS_MODE', 'invalid');
    }
    if (env.NODE_ENV !== undefined && !['development', 'test', 'production'].includes(env.NODE_ENV)) {
        add('NODE_ENV', 'invalid');
    }
    if (local) {
        if (!isLocalApiUrl(env.NEXT_PUBLIC_SUPABASE_URL ?? '')) add('NEXT_PUBLIC_SUPABASE_URL', 'local_only');
        if (!isLocalDatabaseUrl(env.SUPABASE_DATABASE_URL ?? '')) add('SUPABASE_DATABASE_URL', 'local_only');
        if ((env.EZIL_OS_ACCESS_MODE ?? 'invite') !== 'invite') add('EZIL_OS_ACCESS_MODE', 'local_only');
        for (const name of ['CLOUDFLARE_GUACAMOLE_WORKER_URL', 'CLOUDFLARE_GUACAMOLE_HMAC_SECRET']) {
            if (env[name]?.trim()) add(name, 'must_be_unset');
        }
    }
    return issues;
}

/** Never include parser messages, received values, URLs, or exception stacks. */
export function formatDiagnostics(issues: Diagnostic[]): string {
    return issues.map(({ name, code }) => `${name}: ${code}`).join('\n');
}
