'use strict';
const { app, BrowserWindow, ipcMain, session } = require('electron');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const os = require('node:os');
const http = require('node:http');
const { Browser } = require('../src/browser.cjs');
const { Workspaces } = require('../src/workspaces.cjs');
const { senderAllowed, schema } = require('../src/policy.cjs');
const temp = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'ezil-electron-')));
app.setPath('userData', path.join(temp, 'electron'));
setTimeout(() => { console.error('Electron smoke timed out'); app.exit(1); }, 45000).unref();
app.whenReady().then(async () => {
  const store = new Workspaces(path.join(temp, 'data')), a = store.create('A'), b = store.create('B');
  const callers = new Map(); const register = (wc, url, _role, browser) => callers.set(wc.id, { wc, url, browser });
  ipcMain.handle('ezil:native:v1', (event, input) => { const c = callers.get(event.sender.id); assert.ok(senderAllowed(event, c.wc, c.url)); return { ok: true, value: c.browser.action(schema(input)) }; });
  const server = http.createServer((_req, res) => { res.setHeader('Content-Type', 'text/html'); res.end('<title>Test</title><p>Remote page</p>'); });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}/`;
  const first = new Browser(a, register, () => {}), second = new Browser(b, register, () => {});
  await first.tabs[0].view.webContents.loadURL(url); await second.tabs[0].view.webContents.loadURL(url);
  const remote = first.tabs[0].view.webContents;
  assert.equal(await remote.executeJavaScript('typeof require'), 'undefined'); assert.equal(await remote.executeJavaScript('typeof ezilNative'), 'undefined');
  await remote.executeJavaScript('localStorage.setItem("workspace", "A")'); assert.equal(await second.tabs[0].view.webContents.executeJavaScript('localStorage.getItem("workspace")'), null);
  const count = BrowserWindow.getAllWindows().length; await remote.executeJavaScript('window.open("https://example.com")'); assert.equal(BrowserWindow.getAllWindows().length, count);
  assert.equal(first.session.getStoragePath() === second.session.getStoragePath(), false);
  assert.equal(first.tabs[0].view.webContents.getLastWebPreferences().sandbox, true);
  await first.close(); await second.close(); server.close(); await session.defaultSession.clearStorageData();
  fs.rmSync(temp, { recursive: true, force: true }); console.log('Electron GUI/sandbox/partition/popup smoke passed'); app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
